### ISSUE TITLE
Add AndroidDevMetrics

### ISSUE THREAD

**Issue by michaelcarrano** [artem-zinnatullin/qualitymatters#112]
I came across this library recently and it looks interesting. Maybe it would be worth adding to the developer settings?

https://github.com/frogermcs/AndroidDevMetrics

**Comment by artem-zinnatullin** [comment]
Yep, it's interesting lib, wanna do a PR, @michaelcarrano? :)

I'll probably try it in future but no estimates yet.

**Comment by michaelcarrano** [comment]
I may have some time this weekend to work on a PR.

**Comment by lenguyenthanh** [comment]
@michaelcarrano did you do a pr for this? I wanna do it :d

**Comment by michaelcarrano** [comment]
@lenguyenthanh not yet, feel free to do the PR.

**Comment by lenguyenthanh** [comment]
@michaelcarrano Okie, will do ;)

**Comment by lenguyenthanh** [comment]
close as #118

**Comment by michaelcarrano** [comment]
@lenguyenthanh thanks for taking care of this!

**Comment by lenguyenthanh** [comment]
I though I can close :relaxed:

**Comment by artem-zinnatullin** [comment]
Closed by #118!
