### ISSUE TITLE
Add code coverage status to Readme

### ISSUE THREAD

**Issue by lenguyenthanh** [artem-zinnatullin/qualitymatters#119]
It will be great if we have code coverage status of this project. We can use https://coveralls.io or https://codecov.io.

**Comment by artem-zinnatullin** [comment]
Not a fan of badges, but let's try

**Comment by lenguyenthanh** [comment]
It's a good way to make people know the quality of the app and follow #qualitymatters.

**Comment by artem-zinnatullin** [comment]
Closed by #122.
