### ISSUE TITLE
Get rid of Robolectric on DeveloperSettingsTest

### ISSUE THREAD

**Issue by lenguyenthanh** [artem-zinnatullin/qualitymatters#120]
As I see we are using Robolectric to test DeveloperSetting class because DeveloperSetting needs an instance of SharedPreferences. 

Instead of user Robolectric to get SharedPreferences instance we can use some kind of mock or in memory Shared preferences. In my opinion, It will be better approach than using Robolectric.

Or we can use [this](https://github.com/InkApplications/android-preferences) instead of SharedPreferences directly on DeveloperSetting class. It will make mocking stuffs easy.

**Comment by vanniktech** [comment]
#53 is basically saying the same

**Comment by lenguyenthanh** [comment]
Thanks @vanniktech, I joined #53 conversation too, but totally forgot.
Any PR for it yet?

**Comment by vanniktech** [comment]
AFAIK not yet

**Comment by artem-zinnatullin** [comment]
Yup, let's close this as duplicate and fix #53 :)
