### ISSUE TITLE
Take a look at Spring Dependency management plugin

### ISSUE THREAD

**Issue by johnfrey99** [artem-zinnatullin/qualitymatters#126]
https://github.com/spring-gradle-plugins/dependency-management-plugin

When you want to provide dependency management for multiple modules with the same group and version you should use a dependency set. Using a dependency set removes the need to specify the same group and version multiple times:

```
dependencyManagement {
     dependencies {
          dependencySet(group:'org.slf4j', version: '1.7.7') {
               entry 'slf4j-api'
               entry 'slf4j-simple'
          }
     }
}
```

Could be a nicer way to define dependencies especially for things like the android support libraries

**Comment by artem-zinnatullin** [comment]
What problem will it solve for qualitymatters?

**Comment by vanniktech** [comment]
I also don't get it. Maybe that configuration could be used for Google support libraries or Dagger where multiple modules exist and they do share the group id and version.

However that is handled since we separate artifact declaration and version declaration.

**Comment by artem-zinnatullin** [comment]
I'm closing this for now, feel free to comment and we'll probably reopen it.
