### ISSUE TITLE
Add SonarQube

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/qualitymatters#130]
I just read about it [here](https://medium.com/@nielsz/android-quality-with-sonarqube-bf907e614aed#.ya3a0vh0b) and it does seem pretty neat. Unfortunately setting up might be tricky :/

**Comment by artem-zinnatullin** [comment]
Even though it's pretty good, it requires server. Also, it usually uses: FindBugs, PMD, etc as plugins, so I don't really think that we will benefit from it a lot.

**Comment by vanniktech** [comment]
Oh okay I thought it'll do the checks itself and has also some new ones which are not covered by the ones we have.

**Comment by artem-zinnatullin** [comment]
I'm closing this for now then :)
