### ISSUE TITLE
Change Travis CI to something else, it's slow and flaky

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/qualitymatters#132]
Android emulator runs really bad on Travis, pretty often we see that instrumentation tests are not starting because emulator is not responding.

Personally, I'd go with Circle CI for now.

**Comment by vanniktech** [comment]
CircleCI does indeed seem nice though I've never used it. We could also for a while go and have 2 CI's. I've seen that in other projects too. At the end we'll see who we'll cut loose.

**Comment by artem-zinnatullin** [comment]
Good idea, I'll connect Circle CI soon (I use it for personal projects, works fine, though I like Travis UI more)

**Comment by vanniktech** [comment]
Guess this can be closed @artem-zinnatullin ?

**Comment by artem-zinnatullin** [comment]
Ok, I'll remove Travis if I'll see failing builds.
