### ISSUE TITLE
[Question] Unresponsive/Flaky Roboelectric tests

### ISSUE THREAD

**Issue by Plastix** [artem-zinnatullin/qualitymatters#145]
I'm not sure if this is the correct forum for asking this question but I'll ask it anyway.  Hopefully someone has some insight into the problem.

Is anyone else having issues running the unit tests that depend on Roboelectric? For some reason they hang indefinitely on my system. 

See the following test screenshot from Android studio:
<img width="275" alt="screen shot 2016-03-30 at 10 47 41 am" src="https://cloud.githubusercontent.com/assets/1526881/14146225/e089397e-f664-11e5-9d02-e3a20e8a41e4.png">

This problem makes it impossible for me to run unit tests that depend on Android SDK classes.

**Comment by artem-zinnatullin** [comment]
Interesting, what JDK you're building project with?

**Comment by artem-zinnatullin** [comment]
cc @karlicoss have you seen such problem?

**Comment by Plastix** [comment]
@artem-zinnatullin I'm using JDK 1.8.0_40.

**Comment by karlicoss** [comment]
I don't think so. What happens if you run tests directly via Gradle? Does
it happen in qualitymatters only?

Dima Gerasimov, NRU ITMO, study group 4538

**Comment by vanniktech** [comment]
I'm also sometimes having this. It works perfectly fine in the Terminal but AS does not seem to be running Robolectric tests in the last few hours :/

**Comment by Plastix** [comment]
@karlicoss Looks like everything works when I run the tests via Gradle directly. I wonder if this is an Android Studio bug. I am running AS 2.0.0-beta7.

**Comment by artem-zinnatullin** [comment]
I need to check this too, probably they've updated some parts of it (it
downloads some dependencies manually skipping Gradle)

**Comment by vanniktech** [comment]
I'm also having this problem with Gradle Tools 1.5.0. I think the issue is caused by AS (I'm using 2.1.0 alpha preview 4 here)

**Comment by Plastix** [comment]
I'm in the process of writing unit tests for my own MVP app. In my own project, my Roboelectric tests hang when running with Gradle directly as well...

**Comment by artem-zinnatullin** [comment]
Hm, we use Robolectric in NYT and project where @karlicoss works has huge set of Robolectric tests as well and we didn't see such problem (except some concurrency problems with Robolectric that may cause such behavior).

**Comment by artem-zinnatullin** [comment]
@Plastix can you please create an issue in Robolectric repo and add a link to this issue there so we'll very  able to track it.

**Comment by Plastix** [comment]
Thanks for all the feedback @artem-zinnatullin. As many projects use Roboelectric successfully it has to be some quirk of my development environment setup.

**Comment by artem-zinnatullin** [comment]
@Plastix any updates / can we close this?

**Comment by Plastix** [comment]
@artem-zinnatullin I'm still having issues on my system with Roboelectric and AS 2.0.0. I haven't heard back from anyone who maintains Roboelectric. I've been trying to solve this problem for 2 weeks with no luck. Since this isn't an issue with QualityMatters I'll close it.

**Comment by vanniktech** [comment]
Yeah I'm also still having this. Most likely AS changed something :/

**Comment by Plastix** [comment]
@vanniktech My tests still hang when using gradle in the terminal directly as well.

**Comment by vanniktech** [comment]
That has never been the case for me.
