### ISSUE TITLE
Add Gradle Versions Plugin

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/qualitymatters#160]
I'm using this one in my apps and it's fantastic!

https://github.com/ben-manes/gradle-versions-plugin

**Comment by mauricegavin** [comment]
I believe this will be available in AS 2.2 - https://youtu.be/csaXml4xtN8?t=567

**Comment by vanniktech** [comment]
It'll be but you can't use the command line to get the information and also again you don't know how well this will work.

**Comment by artem-zinnatullin** [comment]
👍 I also use this plugin

**Comment by danielgomezrico** [comment]
this is not already done?
https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/build.gradle#L8

**Comment by vanniktech** [comment]
Yup hence closing
