### ISSUE TITLE
Repo as "Awesome"

### ISSUE THREAD

**Issue by danielgomezrico** [artem-zinnatullin/qualitymatters#164]
Hey

Also maybe this repo can be renamed to "Awesome android app" or something since its a refined list of tools and settings all inside one app, also may help to give visibility to this.

Check https://github.com/sindresorhus/awesome

And just wanted to share this awesome with cool plugins/tools/things/any for mobile learning and best practices...

https://github.com/MakinGiants/awesome-mobile-dev

Its aligned with quality matters so maybe add it to readme here as reference or an update from you guys it with cool things learned from here or something will be "awesome" (lol).

**Comment by danielgomezrico** [comment]
Naa this doesnt make sense, an "awesome" is another thing...

**Comment by artem-zinnatullin** [comment]
:)
