### ISSUE TITLE
androidGradlePlugin in dependencies

### ISSUE THREAD

**Issue by IgorGanapolsky** [artem-zinnatullin/qualitymatters#181]
Hello,
can you tell me what the significance of this item is in your **dependencies.gradle**:
`androidGradlePlugin          : '2.0.0'`

It is not used anywhere at all.  Can you tell me what the 2.0.0 refers to?

Thank you,
Igor

**Comment by artem-zinnatullin** [comment]
It is used in [`dependencies.gradle` below](https://github.com/artem-zinnatullin/qualitymatters/blob/bb0faa20ad1c70a429dedca4233982f3c5bdc7bd/dependencies.gradle#L51).

Concept here is that all versions are in `version` map, all artifacts are in `libraries` and `gradlePlugins` maps.

**Comment by IgorGanapolsky** [comment]
I see.  Unfortunately when I do a global search in Android Studio 2.2 for **androidGradlePlugin**, it returns no results because this string is in a Groovy closure.  Very confusing.

**Comment by IgorGanapolsky** [comment]
@artem-zinnatullin Thanks for this nice sample!  @changetip $1

**Comment by changetip** [comment]
Hi @artem-zinnatullin, @IgorGanapolsky sent you a tip worth 1,449 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/948385)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by artem-zinnatullin** [comment]
Hah, thanks :D
