### ISSUE TITLE
Upgrade Robolectric to 3.1

### ISSUE THREAD

**Issue by Plastix** [artem-zinnatullin/qualitymatters#186]
Robolectric now supports "emulating" SDK 23. Note that the Robolectric Config class constructor for the test runner has changed: http://robolectric.org/javadoc/3.1/org/robolectric/annotation/Config.Implementation.html

Seems like the only required changes for me.

**Comment by artem-zinnatullin** [comment]
There are several new parameters in that constructor

**Comment by Plastix** [comment]
Oh I totally missed that. I'll submit a PR later when I get the chance.

**Comment by artem-zinnatullin** [comment]
Ok :+1:
