### ISSUE TITLE
Question regarding onDestroyView()

### ISSUE THREAD

**Issue by david-perez** [artem-zinnatullin/qualitymatters#199]
```
@Override
    public void onDestroyView() {
        itemsPresenter.unbindView(this);

        if (unbinder != null) {
            unbinder.unbind();
        }

        super.onDestroyView();
    }
```

Excerpt from [here](https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/src/main/java/com/artemzin/qualitymatters/ui/fragments/ItemsFragment.java).

AS code inspection warns that `if (unbinder != null)` condition is always `true`. As the unbinder is tied to the activity/fragment lifecycle, and we don't modify the `unbinder` anywhere, I don't see how it may become `null`.

Also, we need to unbind the view from the presenter every time `onDestroyView()/onDestroy()` is called on activities/fragments. Couldn't we hold a reference to a generic `Presenter` in `BaseActivity/BaseFragment` to call `super()` and avoid having to write this method every single time?

**Comment by vanniktech** [comment]
AFAIK Findbugs complained about this one line and I just added that null check.

**Comment by david-perez** [comment]
Any comments about the second part of my question?

**Comment by artem-zinnatullin** [comment]
Second part: yes you can do it in base classes, but personally I just don't
like such inheritance behavior, it makes code implicit.

Also, for example at the moment I use MVVM at work and our app has old
parts in MVP and new in MVVM, since our base classes does not know about
MVP or MVVM we don't have problems with using two different design patterns
in one project :)

**Comment by david-perez** [comment]
I would very much be interested in seeing a rewrite of QualityMatters using MVVM + [RxUi](https://artemzin.com/blog/rxui-talking-to-android-view-layer-in-a-reactive-way/) (https://github.com/artem-zinnatullin/qualitymatters/issues/195, https://github.com/artem-zinnatullin/qualitymatters/issues/42).

**Comment by artem-zinnatullin** [comment]
Yeah, me too! Planned to do after vacation
