### ISSUE TITLE
Syncing developer settings in between activities

### ISSUE THREAD

**Issue by david-perez** [artem-zinnatullin/qualitymatters#200]
Say there are two activities, `A` and `B`, which both have a `ViewModifier` that inserts a `DeveloperSettingsFragment` inside a `FrameLayout`.
1. Navigate from activty `A` to activity `B`.
2. Change a developer setting using the `DeveloperSettingsFragment`.
3. Navigate back to activity `A`.
4. Open the `FrameLayout` to see current developer settings.

Observed behaviour: although the developer settings have correctly been updated in the `DeveloperSettingsModel`, the UI of activity `A` shows the old developer settings being enabled.

Expected behabiour: the UI of activity `A` should reflect the updated and currently enabled developer settings.

**Comment by david-perez** [comment]
The cause of this is that because activity `A` is still in the back stack, when one returns to activity `A` `onCreateView()` in `DeveloperSettingsFragment` is not called.

I propose the following fix.

Override `onResume()` in `DeveloperSettingsFragment`:

```
@Override
public void onResume() {
    super.onResume();
    presenter.syncDeveloperSettings();
}
```

Add `syncDeveloperSettings()` to `DeveloperSettingsPresenter`:

```
public void syncDeveloperSettings() {
    DeveloperSettingsView view = view();

    view.changeGitSha(developerSettingsModel.getGitSha());
    view.changeBuildDate(developerSettingsModel.getBuildDate());
    view.changeBuildVersionCode(developerSettingsModel.getBuildVersionCode());
    view.changeBuildVersionName(developerSettingsModel.getBuildVersionName());
    view.changeStethoState(developerSettingsModel.isStethoEnabled());
    view.changeLeakCanaryState(developerSettingsModel.isLeakCanaryEnabled());
    view.changeTinyDancerState(developerSettingsModel.isTinyDancerEnabled());
    view.changeHttpLoggingLevel(developerSettingsModel.getHttpLoggingLevel());
}
```

This method will also be called in `bindView()`, when the view is being created for the first time:

```
@Override
public void bindView(@NonNull DeveloperSettingsView view) {
    super.bindView(view);

    syncDeveloperSettings();
}
```

**Comment by artem-zinnatullin** [comment]
Sounds good to me
