### ISSUE TITLE
Java code styles

### ISSUE THREAD

**Issue by VasileUngureanu** [artem-zinnatullin/qualitymatters#201]
Hi, what you guys think about code styles (code formatting)? Is an important thing for quality? You use standard (AS) code styles or custom one (like square code styles).

Thanks!

**Comment by atetc** [comment]
CodeStyles nice feature of Android Studio that allow us use different styles in different teams. For maintain it the best way is to put xml file in repository and continuously improve it using PR.

**Comment by artem-zinnatullin** [comment]
Yup, we do that at work, I see no reasons why not do this for qualitymatters

**Comment by emartynov** [comment]
Guys, can you merge PR?

**Comment by artem-zinnatullin** [comment]
Done!
