### ISSUE TITLE
Code Quality Tools: PMD

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/qualitymatters#44]
I really do like to use [PMD](https://pmd.github.io/) as it catches some stuff that neither Checkstyle nor Findbugs does.

If you want me to, I could also add that one, we'd just then need to agree on some rules as there are quite a lot.

**Comment by artem-zinnatullin** [comment]
It's already used! See root `build.gradle`! Feel free to suggest rules.

**Comment by vanniktech** [comment]
Ups. Sorry I was confused because I could not find the configuration file in the `code_quality_tools` directory. I'll take a look tomorrow at the rules.

**Comment by artem-zinnatullin** [comment]
:+1:
