### ISSUE TITLE
Document Developer Settings

### ISSUE THREAD

**Issue by jpshelley** [artem-zinnatullin/qualitymatters#45]
Really liking the debug panel. I noticed it in Wharton's U2020, and was curious if yours is a clone or if you've modified it in some ways. I know there are a couple 3rd party libraries that are similar as well.
Would be nice to update the README to document it in some form.

**Comment by artem-zinnatullin** [comment]
QualityMatters has its own implementation of Developer Settings based on my
experience of how I do it in production apps.

You want to see more detailed explanation of how Developer Setting are
built in the app in the README?

On Thu, Dec 3, 2015, 23:37 John Shelley <notifications@github.com> wrote:

> Really liking the debug panel. I noticed it in Wharton's U2020, and was
> curious if yours is a clone or if you've modified it in some ways. I know
> there are a couple 3rd party libraries that are similar as well.
> Would be nice to update the README to document it in some form.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/45>.
>
-- 

@artem_zin

**Comment by jpshelley** [comment]
@artem-zinnatullin Yeah or even throw it into a library and put it up on jcenter :smiley:
Besides yours and whartons I've seen: https://github.com/palaima/DebugDrawer
Always like to see more out in the wild though to try out.

**Comment by artem-zinnatullin** [comment]
Okay, I'll describe basic things about Developer Settings in the README.

Not sure I want to turn it into a library because it should be easy to
setup and customizable at the same time. Also, it's just hard to decide
what to extract to the library and what not  ¯\_(ツ)_/¯

On Fri, Dec 4, 2015, 00:17 John Shelley <notifications@github.com> wrote:

> @artem-zinnatullin <https://github.com/artem-zinnatullin> Yeah or even
> throw it into a library and put it up on jcenter [image: :smiley:]
> Besides yours and whartons I've seen:
> https://github.com/palaima/DebugDrawer
> Always like to see more out in the wild though to try out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/45#issuecomment-161787383>
> .
>
-- 

@artem_zin
