### ISSUE TITLE
Process Phoenix for activity restart 

### ISSUE THREAD

**Issue by aashrairavooru** [artem-zinnatullin/qualitymatters#58]
Instead of prompting everytime to restart the  app we can use process Phoenix https://github.com/JakeWharton/ProcessPhoenix

**Comment by artem-zinnatullin** [comment]
Yep, but probably developer/qa wants to enable/disable multiple things in Developer Settings and only then restart the app.

Though I'm okay with "Restart app" button in Developer Settings :)

**Comment by aashrairavooru** [comment]
Yeah I also had this use case where I wanted to selectively switch off
cache for certain apis, I tend to put a button on top in the debug drawer
which relaunches the activity using process Phoenix underneath makes the
whole thing faster

**Comment by artem-zinnatullin** [comment]
Closed by #152.
