### ISSUE TITLE
Add errorprone

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/qualitymatters#67]
Basically that tool automatically hooks itself up with the build process so even locally while developing you'll get warnings / errors. If it's fatal it'll give you an error during compiling.

[Website for more information](http://errorprone.info/)

If you want, I can also submit a PR for that in the next couple of days.

**Comment by artem-zinnatullin** [comment]
Would be great!

On Fri, Dec 18, 2015, 02:45 Niklas Baudy <notifications@github.com> wrote:

> Basically that tool automatically hooks itself up with the build process
> so even locally while developing you'll get warnings / errors. If it's
> fatal it'll give you an error during compiling.
>
> Website for more information <http://errorprone.info/>
>
> If you want, I can also submit a PR for that in the next couple of days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/67>.
>
-- 

@artem_zin
