### ISSUE TITLE
Dagger Note

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/qualitymatters#78]
While running the project locally I got that note.

> Note: Generating a MembersInjector or Factory for com.artemzin.qualitymatters.QualityMattersApp. Prefer to run the dagger processor over that class instead.

Should we pay attention to this one?

**Comment by artem-zinnatullin** [comment]
I don't think it's a problem, I probably saw something about false-positive warnings in Dagger's issues. And we 100% have same warnings in our production apps. Is #qualitymatters the first app where you see such warning?

**Comment by vanniktech** [comment]
Yes it is.

**Comment by artem-zinnatullin** [comment]
Haha :) Not really, if you'll investigate it, please share the results
here!

On Fri, 29 Jan 2016, 22:50 Leo Wandersleb <notifications@github.com> wrote:

> So I assume this is a hint to do something better but googling it, only
> got me here. Any pointers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/78#issuecomment-176938320>
> .
>
-- 

@artem_zin

**Comment by artem-zinnatullin** [comment]
Just linking issue created in Dagger 2 for that https://github.com/google/dagger/issues/328

**Comment by vanniktech** [comment]
I guess this can be closed in favor of the one we created at Google's dagger project?

**Comment by artem-zinnatullin** [comment]
Let's leave it for now, I'd prefer to close it when we'll fix it in qualitymatters too :)

**Comment by vanniktech** [comment]
Closing since we don't `@Inject` anymore into application class

**Comment by artem-zinnatullin** [comment]
Yup, thanks!
