### ISSUE TITLE
Gradle sync fails all the time

### ISSUE THREAD

**Issue by agap** [artem-zinnatullin/qualitymatters#93]
I'm running `sh ci.sh` and the project is built successfully.
However, Android Studio keeps showing me the following error message:

> Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly

Because whenever I try to sync Gradle project I'm getting the following error:

> Error:(4, 0) Cause: hu/supercluster/paperwork/plugin/PaperworkPlugin : Unsupported major.minor version 52.0

I suppose that this may be caused by the incompatibility of bytecode generated by different java compilers. The `JAVA_HOME` on my system points to the Java 7 installation, the `javac -version` output is the 

> javac 1.7.0_80

...and the `java -version` gives me 

> java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Where does this error may come from?

**Comment by artem-zinnatullin** [comment]
I guess you need JDK 8

**Comment by artem-zinnatullin** [comment]
Let's ask @zsoltk if it's possible to recompile Paperwork with target and compile bytecode level JDK 6 and upload a new version

**Comment by agap** [comment]
I forgot to mention that I was using JDK 8 before: `JAVA_HOME` was pointing to Java 8 installation and both `java -version` and `javac -version` were showing that I use Java 8. I thought that `PaperworkPlugin` is incompatible with Java 8, switched to Java 7 - the issue persists.

**Comment by agap** [comment]
Well, the `sh ci.sh` runs fine and it invokes more or less the same gradle tasks that I try to run in the Android Studio `Gradle` tab. I suppose `Android Studio` somehow uses the wrong JRE but can not figure out which setting I have to change.

**Comment by artem-zinnatullin** [comment]
Yup, Android Studio 2 uses own bundled JDK, you can find its version in
"About" window. Though, it works fine on mine machines with Mac OS and
Android Studio 2.

On Tue, 16 Feb 2016, 11:12 Artem Gapchenko <notifications@github.com> wrote:

> Well, the sh ci.sh runs fine and it invokes more or less the same gradle
> tasks that I try to run in the Android Studio Gradle tab. I suppose Android
> Studio somehow uses the wrong JRE but can not figure out which setting I
> have to change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/93#issuecomment-184749510>
> .
>
-- 

@artem_zin

**Comment by agap** [comment]
Okay, now build works fine and I cannot break it again.
What I did (possibly one of those actions fixed my build):
* changed the javac version to 1.7
* changed the java version to 1.7
* changed the content of JAVA_HOME so it points to Java 7
* removed everything in `build` subfolders.

**Comment by artem-zinnatullin** [comment]
Ah, yeah, let's anyway wait for feedback from @zsoltk :)

**Comment by zsoltk** [comment]
It has already been recompiled with 1.6, just update paperwork dependency to 1.2.4 :)
